### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Tilin88** [oxiKKK/oxware#20]
Windows Defender detects the oxware.exe file as a severe risk Trojan, more specifically Behavior:Win32/DefenseEvasion.A!ml.
why?

**Comment by daraleak** [comment]
bcz all cheat works like trojan bro
click on the antivirus to allow this the threat, since this is the code from the github and there can be no viruses

**Comment by daraleak** [comment]
> Windows Defender detects the oxware.exe file as a severe risk Trojan, more specifically Behavior:Win32/DefenseEvasion.A!ml. why?

bcz all cheat works like trojan bro
click on the antivirus to allow this the threat, since this is the code from the github and there can be no viruses

**Comment by Tilin88** [comment]
thanks bro, but what can a cheat have to detect it as a trojan¿

**Comment by oxiKKK** [comment]
Hi. As @daraleak pointed out, cheats are usually detected as malware by WD, because of two things:
1. Windows defender is stupid. I usually make up my own applications and WD detects them as virus for no reason, which is funny.
2. The cheat has injector that basically injects code into the game. This could be suspicious for the anticheat-software. 

With that being said, there is no malware or data collecting software in my cheat. If you don't believe me - sure - see the code, it's there 😉

Closing this issue.
