### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by Nord1cWarr1or** [oxiKKK/oxware#3]
Yes, I read the readme, but
>This cheat is __currently__ only available on Windows 10 and newer.

it says "currently".. I mean, do you have plans to make this project cross-platform in the future?

**Comment by oxiKKK** [comment]
Hi, yes, while this isn't completely impossible, it would be quite a lot of work, because from the beginning I have led the development towards Windows only. But yeah, it is possible for sure, maybe in the future...? 😬

But more importantly, what I meant by that statement is more like support for older Windows versions (e.g. Windows 7/8), rather than making the cheat cross-platform. 🙂

**Comment by Nord1cWarr1or** [comment]
Ok, thanks for the answer.  I will wait, if it can be done
